name: Multiple Runner
on: 
 workflow_dispatch:
    inputs:
      runner:
        description: 'select the runner'
        required: true
        type: string
      jobs-name:
        description: 'Enter the job name'
        required: true
        type: string
jobs: 
  build:
   continue-on-error: true
   if: ${{ contains(github.event.inputs.jobs-name, 'build') }}
   runs-on: ${{ github.event.inputs.runner }}
   steps: 
    - name: build the code 
      run: echo "Build the code"

  test:
   if: ${{ contains(github.event.inputs.jobs-name, 'test') }}
   runs-on: ${{ github.event.inputs.runner }}
   steps:
    - name: Executes test cases
      run: echo "Execute the test cases"
  deploy:
   if: ${{ contains(github.event.inputs.jobs-name, 'deploy') }} 
   runs-on: ${{ github.event.inputs.runner }} 
   steps:
     - name: Deploy the code 
       run: echo "Deploy the code"
